### PR TITLE
Make binaries executable in migration

### LINKED ISSUE #2: Does not install through settings (I get an error) and ignores app store install
### Steps to reproduce
1. Go to the app store and install Talk matterbridge
2. Go to settings>talk 
3. You will see the screen (see attached image) 
4. Click on "Install Matterbridge"
5. Nothing happens - as it says on the description, it's probably timing out. 

### Expected behaviour
1. I would expect that after installing "Talk Matterbridge" from the app store, it would already be available to me in settings OR at the least, I enable it in the Talk settings. 
2. If I install from the settings, it shouldn't throw an error 

### Actual behaviour
Installing "talk matterbridge" doesn't work 

## Server configuration detail

**Operating system:** Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.0 Beta 2 - 20.0.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.1
 - admin_audit: 1.10.0
 - bookmarks: 3.3.4
 - calendar: 2.0.4
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.3.0
 - contactsinteraction: 1.1.0
 - dav: 1.16.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - duplicatefinder: 0.0.2
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.O
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - gpxpod: 4.2.2
 - issuetemplate: 0.6.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.4.1
 - metadata: 0.12.0
 - news: 14.1.11
 - nextbackup: 20.4.0
 - nextcloud_announcements: 1.9.0
 - notes: 3.6.4
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - occweb: 0.0.7
 - onlyoffice: 4.3.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - rainloop: 7.0.2
 - riotchat: 0.6.4
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.0-beta.1
 - support: 1.3.0
 - survey_client: 1.8.0
 - suspicious_login: 3.1.0
 - systemtags: 1.10.0
 - talk_matterbridge: 1.18.1
 - tasks: 0.13.3
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 0.0.2
 - viewer: 1.4.0
 - workflowengine: 2.2.0
Disabled:
 - apporder
 - audioplayer
 - bruteforcesettings
 - camerarawpreviews
 - dashboard
 - drawio
 - encryption
 - event_update_notification
 - external
 - files_external
 - files_markdown
 - firstrunwizard
 - forms
 - guests
 - impersonate
 - maps
 - music
 - phonetrack
 - previewgenerator
 - recommendations
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "aproposnix.dyndns.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.0.4",
    "overwrite.cli.url": "https:\/\/aproposnix.dyndns.org\/",
    "Overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "app_install_overwrite": [
        "social",
        "dashboard",
        "occweb",
        "issuetemplate",
        "suspicious_login",
        "calendar",
        "onlyoffice",
        "documentserver_community",
        "news",
        "riotchat",
        "contacts",
        "spreed",
        "initialcheck",
        "rainloop"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "updater.release.channel": "beta",
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0

**Operating system:** Ubuntu 20.04

Selection_116

Screenshot from 2020-08-28 12-00-47

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #2

While it would be possible to make just the binary being used executable, thought it would be a good idea to make them all executable in case the sysadmin moves the server from one architecture to another.

### CODE REVIEW

File: lib/Migration/RegisterBinary.php [hunk 1]
```diff
@@ -67,6 +67,11 @@ public function run(IOutput $output): void {
 			}
 		}
 
+		// Make all binaries executable
+		chmod($binaryDir . "matterbridge-" . self::VERSION . '-linux-arm64', 0755);
+		chmod($binaryDir . "matterbridge-" . self::VERSION . '-linux-64bit', 0755);
+		chmod($binaryDir . "matterbridge-" . self::VERSION . '-linux-32bit', 0755);
```
Comment (nickvergessen) [inline lib/Migration/RegisterBinary.php:73]:
```suggestion
		chmod($binaryPath , 0755);
```

We will only execute this anyway

Comment (gary-kim) [reply lib/Migration/RegisterBinary.php:73]: Oh, wait, it wouldn't work anyways unless the migration is rerun if the server is moved to another architecture. Didn't think about that.

**Review by nickvergessen — APPROVED** [review]
